<!DOCTYPE html>
<html>
    <head>
        <meta charset=utf-8 />
        <?=$this->tag->getTitle() ?>
        <link rel="stylesheet" type="text/css" media="screen" href="css/master.css" />
    </head>
    <body>
        <h1>Layout</h1>       
        <?php if(!empty($this->flashSession->getMessages(null, false))):?>
            <div class="flash"><?=$this->flashSession->output()?></div>        
        <?php endif;?>
        <?=$this->partial('layout/menu')?>
        <?=$this->getContent()?>
    </body>
</html>